In [16]:
# Import library
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [17]:
data_startup = pd.read_csv('50_Startups.csv')

In [58]:
data_startup.sample(7)

R&D Spend  Administration  Marketing Spend       State     Profit
44   22177.74       154806.14         28334.72  California   65200.33
11  100671.96        91790.61        249744.55  California  144259.40
14  119943.24       156547.42        256512.92     Florida  132602.65
49        NaN       116983.80         45173.06  California   14681.40
40   28754.33       118546.05        172795.67  California   78239.91
39   38558.51        82982.09        174999.30  California   81005.76
29   65605.48       153032.06        107138.38    New York  101004.64

In [70]:
X = data_startup.sample(7).values
X 

array([[114523.61, 122616.84, 261776.23, 'New York', 129917.04],
       [28754.33, 118546.05, 172795.67, 'California', 78239.91],
       [46426.07, 157693.92, 210797.67, 'California', 96712.8],
       [119943.24, 156547.42, 256512.92, 'Florida', 132602.65],
       [120542.52, 148718.95, 311613.29, 'New York', 152211.77],
       [130298.13, nan, 323876.68, 'Florida', 155752.6],
       [nan, 110594.11, 229160.95, 'Florida', 146121.95]], dtype=object)

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [71]:
X

array([[114523.61, 122616.84, 261776.23, 'New York', 129917.04],
       [28754.33, 118546.05, 172795.67, 'California', 78239.91],
       [46426.07, 157693.92, 210797.67, 'California', 96712.8],
       [119943.24, 156547.42, 256512.92, 'Florida', 132602.65],
       [120542.52, 148718.95, 311613.29, 'New York', 152211.77],
       [130298.13, nan, 323876.68, 'Florida', 155752.6],
       [nan, 110594.11, 229160.95, 'Florida', 146121.95]], dtype=object)

In [72]:
label_encoder = LabelEncoder()
X[:, -2] =label_encoder.fit_transform(X[:,-2])
X

array([[114523.61, 122616.84, 261776.23, 2, 129917.04],
       [28754.33, 118546.05, 172795.67, 0, 78239.91],
       [46426.07, 157693.92, 210797.67, 0, 96712.8],
       [119943.24, 156547.42, 256512.92, 1, 132602.65],
       [120542.52, 148718.95, 311613.29, 2, 152211.77],
       [130298.13, nan, 323876.68, 1, 155752.6],
       [nan, 110594.11, 229160.95, 1, 146121.95]], dtype=object)

In [73]:
one_hot_encoder = OneHotEncoder(categories=X[0])
ct = ColumnTransformer([("Name_Of_Your_Step", OneHotEncoder(),[0])], remainder="passthrough")
X = ct.fit_transform(X)
# X = one_hot_encoder.fit_transform(X).toarray()
df = pd.DataFrame(X)
df

0    1    2    3    4    5    6          7          8  9          10
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  122616.84  261776.23  2  129917.04
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  118546.05  172795.67  0   78239.91
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  157693.92  210797.67  0    96712.8
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  156547.42  256512.92  1  132602.65
4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  148718.95  311613.29  2  152211.77
5  0.0  0.0  0.0  0.0  0.0  1.0  0.0        NaN  323876.68  1   155752.6
6  0.0  0.0  0.0  0.0  0.0  0.0  1.0  110594.11  229160.95  1  146121.95

In [78]:
X =X.astype(int)
X

array([[          0,           0,           2,           0,           0,
                  0,           0,           0,           0,           1,
                  0],
       [          2,           0,           0,           0,           0,
                  0,           0,           0,          -1,          -1,
                 -1],
       [          0,           2,           0,           0,           0,
                  0,           0,           1,           0,          -1,
                 -1],
       [          0,           0,           0,           2,           0,
                  0,           0,           1,           0,           0,
                  0],
       [          0,           0,           0,           0,           2,
                  0,           0,           0,           1,           1,
                  0],
       [          0,           0,           0,           0,           0,
                  2,           0, -2147483648,           1,           0,
              

In [79]:
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[-0.40824829, -0.40824829,  2.44948974, -0.40824829, -0.40824829,
        -0.40824829, -0.40824829,  0.40824829, -0.2236068 ,  1.32287566,
         0.2236068 ],
       [ 2.44948974, -0.40824829, -0.40824829, -0.40824829, -0.40824829,
        -0.40824829, -0.40824829,  0.40824829, -1.78885438, -1.32287566,
        -1.34164079],
       [-0.40824829,  2.44948974, -0.40824829, -0.40824829, -0.40824829,
        -0.40824829, -0.40824829,  0.40824829, -0.2236068 , -1.32287566,
        -1.34164079],
       [-0.40824829, -0.40824829, -0.40824829,  2.44948974, -0.40824829,
        -0.40824829, -0.40824829,  0.40824829, -0.2236068 ,  0.        ,
         0.2236068 ],
       [-0.40824829, -0.40824829, -0.40824829, -0.40824829,  2.44948974,
        -0.40824829, -0.40824829,  0.40824829,  1.34164079,  1.32287566,
         0.2236068 ],
       [-0.40824829, -0.40824829, -0.40824829, -0.40824829, -0.40824829,
         2.44948974, -0.40824829, -2.44948974,  1.34164079,  0.        ,
         1.788